name: Copy branches | main -> documentation 

env:
  GITHUB_USER: hannesdelbeke
  GITHUB_REPO: notes
  BRANCH_SOURCE: main
  BRANCH_PUBLISH: documentation


# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-images:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy Images
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.ACTION_TOKEN  }}
          src_branch: $BRANCH_SOURCE
          src_path: /images/.
          dst_owner: $GITHUB_USER
          dst_repo_name: $GITHUB_REPO
          dst_path: /static/images/
          dst_branch: $BRANCH_PUBLISH
          clean: true
          commit_message: "Images copied from main to documentation branch!"

  copy-sections:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy Markdowns
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.ACTION_TOKEN  }}
          src_branch: $BRANCH_SOURCE
          src_path: /sections/.
          dst_owner: $GITHUB_USER  # what's this for?
          dst_repo_name: $GITHUB_REPO  # what's this for?
          dst_path: /docs/
          dst_branch: $BRANCH_PUBLISH
          clean: true
          commit_message: "Sections copied from main to documentation branch!"
# copy-readme:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - name: Copy Markdowns
#       uses: andstor/copycat-action@v3
#       with:
#         personal_token: ${{ secrets.PERSONAL_TOKEN  }}
#         src_branch: main
#         src_path: /README.md
#         dst_owner: andkret
#         dst_repo_name: Cookbook
#         dst_path: /docs/
#         dst_branch: documentation
#         commit_message: "README.md copied from main to documentation branch!"
